### ISSUE TITLE
Making it work on python3.10

### ISSUE THREAD

**Issue by karen-pal** [Ho011/pyraylib#2]
Hello, thanks for your work. Your library is awesome!

When trying to run on python3.10 a simple file with just a pyraylib import, an error message appears

`ImportError: cannot import name 'Iterable' from 'collections'
`

Changing [this line](https://github.com/Ho011/pyraylib/blob/main/pyraylib/__init__.py#L8) 

from

```python
from collections import (
    Iterable
)
```

to
```python
from collections.abc import (
    Iterable
)
```
made it work completely.

I wouldn't mind making a PR with this change. Hope this helps anyone trying to work with this nice library.

Cheers.

**Comment by 7s9n** [comment]
Thanks for the bug report @karen-pal . It'll be great, if you make a PR as soon as possible.
