### PR TITLE
Making it work on python3.10

### LINKED ISSUE #2: Making it work on python3.10
Hello, thanks for your work. Your library is awesome!

When trying to run on python3.10 a simple file with just a pyraylib import, an error message appears

`ImportError: cannot import name 'Iterable' from 'collections'
`

Changing [this line](https://github.com/Ho011/pyraylib/blob/main/pyraylib/__init__.py#L8) 

from

```python
from collections import (
    Iterable
)
```

to
```python
from collections.abc import (
    Iterable
)
```
made it work completely.

I wouldn't mind making a PR with this change. Hope this helps anyone trying to work with this nice library.

Cheers.

### PR DESCRIPTION
**Pull request by karen-pal**
Changes:
- Iterable is imported from collections.abc instead of plain collections library, on pyraylib/__init__.py

Closes #2

### CODE REVIEW

**Comment by 7s9n** [comment]
Hi @karen-pal , I think you should consider **backward compatibility**.
please edit your code something like:
```
try:
    from collections.abc import Iterable
except ImportError:
    from collections import Iterable
```

or correct me if i'm wrong.

**Comment by karen-pal** [comment]
@Ho011 Yes, you are right! just added your code block!
